# Generated by Django 5.2.3 on 2025-07-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('OrderPlaced', 'OrderPlaced'), ('Shipped', 'Shipped'), ('OutForDelivery', 'OutForDelivery'), ('Delivered', 'Delivered'), ('cancelled', 'cancelled')], default='OrderPlaced', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('SmartPhone', 'SmartPhone'), ('Tablet', 'Tablet'), ('SmartWatch', 'SmartWatch'), ('LapTop', 'LapTop'), ('Headphones', 'Headphones'), ('Camera', 'Camera'), ('GamingConsole', 'Gaming Console'), ('Accessories', 'Accessories')], max_length=100),
        ),
    ]
